Re-enables the battery charger.
Miovision/royaloak-linux-tegra-4.9 pull request #77
Opened 2021-03-12 13:46 UTC by macorke

Found that this needs to be enabled, then disabled at runtime.

2021-03-12 13:46 UTC, MikeLoder requested changes

2021-03-12 13:46 UTC, MikeLoder commented on nvidia/platform/t19x/galen/kernel-dts/tegra194-p2888-0001-royaloak-dcm.dts
>      // Disable the battery backup charging as we are using a coin cell.
The comment no longer matches whats happening

2021-03-12 13:56 UTC, MikeLoder approved these changes, later dismissed
Thanks

2021-03-12 15:08 UTC, m3harvey submitted a review, later dismissed

2021-03-15 19:04 UTC, MikeLoder approved these changes

2021-03-15 19:38 UTC, m3harvey approved these changes

2021-03-15 19:51 UTC, merged